[theme]
# base="light"
# # Primary accent for interactive elements
# primaryColor = "#f77b7d"

# # Background color for the main content area
# backgroundColor = "#baeef1"

# # Background color for sidebar and most interactive widgets
# secondaryBackgroundColor = "#eca1ad"

# # Color used for almost all text
# textColor = '#FFFFFF'

# # Font family for all text in the app, except code blocks
# # Accepted values (serif | sans serif | monospace) 
# # Default: "sans serif"
# font = "sans serif"


# Dracula Theme
primaryColor="#bd93f9"
backgroundColor="#282a36"
secondaryBackgroundColor="#44475a"
textColor="#f8f8f2"
